// auto-generated
// Code generated by GUI builder.

package main

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win fyne.Window

	feed *widget.List
	nav  *container.Navigation
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.feed = widget.NewList(func() int {
		return 5
	}, func() fyne.CanvasObject {
		return widget.NewLabel("Template Object")
	}, func(id widget.ListItemID, item fyne.CanvasObject) {
		item.(*widget.Label).SetText(fmt.Sprintf("Item %d", id+1))
	})
	g.nav = container.NewNavigationWithTitle(
		container.NewStack(
			g.feed), "/.")

	return container.NewStack(
		g.nav)
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("main")
	g.win = w
	w.Resize(fyne.NewSize(476, 415))
	w.SetContent(g.makeUI())
	return w
}