// auto-generated
// Code generated by GUI builder.

package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type viewGui struct {
	win fyne.Window

	content *widget.RichText
	open    *widget.Button
	section *canvas.Image
	share   *widget.Button
	time    *canvas.Text
	title   *widget.RichText
}

func newViewGUI() *viewGui {
	return &viewGui{}
}

func (g *viewGui) makeUI() fyne.CanvasObject {
	g.content = widget.NewRichTextFromMarkdown(`Article content

* stuff`)
	g.open = widget.NewButton("Open  on Slashdot", func() {})
	g.section = func() *canvas.Image {
		img := &canvas.Image{File: "/Users/andy/Code/Andy/slashread/Icon.png", FillMode: canvas.ImageFillContain, CornerRadius: 0.000000}
		img.SetMinSize(fyne.Size{Width: 32, Height: 32})
		return img
	}()
	g.share = widget.NewButtonWithIcon("", theme.UploadIcon(), func() {})
	g.time = &canvas.Text{Alignment: 0, Color: color.NRGBA{R: 0xff, G: 0x98, B: 0x0, A: 0xff}, Text: "Text", TextSize: 11, TextStyle: fyne.TextStyle{Bold: false, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false}, FontSource: nil}
	g.title = widget.NewRichTextFromMarkdown(`# Article`)

	return container.NewBorder(
		nil,

		container.NewBorder(
			nil,
			nil,
			nil,

			g.share,
			g.open),
		nil,
		nil,
		container.NewScroll(
			container.NewBorder(

				container.NewBorder(
					nil,
					nil,
					nil,

					container.NewVBox(
						container.NewPadded(
							g.section)),
					container.NewVBox(
						g.title,
						container.NewPadded(
							g.time))),
				nil,
				nil,
				nil,
				g.content)))
}

func (g *viewGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("view")
	g.win = w
	w.Resize(fyne.NewSize(341, 226))
	w.SetContent(g.makeUI())
	return w
}
