// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
	"image/color"
)

type viewGui struct {
	win fyne.Window

	content *widget.RichText
	open    *widget.Button
	share   *widget.Button
	time    *canvas.Text
	title   *widget.RichText
}

func newViewGUI() *viewGui {
	return &viewGui{}
}

func (g *viewGui) makeUI() fyne.CanvasObject {
	g.content = widget.NewRichTextFromMarkdown(`Article content

* stuff`)
	g.open = widget.NewButton("Open  on Slashdot", func() {})
	g.share = widget.NewButtonWithIcon("", theme.UploadIcon(), func() {})
	g.time = &canvas.Text{Alignment: 0, Color: &color.NRGBA{R: 0xff, G: 0x98, B: 0x0, A: 0xff}, Text: "Post time", TextSize: 11, TextStyle: fyne.TextStyle{Bold: false, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false}, FontSource: nil}
	g.title = widget.NewRichTextFromMarkdown(`# Article`)

	return container.NewBorder(

		container.NewVBox(
			g.title,
			container.NewPadded(
				g.time)),

		container.NewBorder(
			nil,
			nil,
			nil,

			g.share,
			g.open),
		nil,
		nil,
		g.content)
}

func (g *viewGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("view")
	g.win = w
	w.Resize(fyne.NewSize(337, 226))
	w.SetContent(g.makeUI())
	return w
}